project_id = "voolvfxtegcebfvsdijz"

[functions.import-contacts]
verify_jwt = true

[functions.send-campaign]
verify_jwt = true

[functions.manage-tenants]
verify_jwt = false

[functions.manage-tenant-settings]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.complete-invitation]
verify_jwt = false

[functions.process-campaign-queue]
verify_jwt = false
