project_id = "voolvfxtegcebfvsdijz"

[functions.create-contact]
verify_jwt = false

[functions.sync-contact-from-external]
verify_jwt = false

[functions.import-contacts]
verify_jwt = false

[functions.send-campaign]
verify_jwt = true

[functions.manage-tenants]
verify_jwt = false

[functions.manage-tenant-settings]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.complete-invitation]
verify_jwt = false

[functions.process-campaign-queue]
verify_jwt = false

[functions.initiate-oauth]
verify_jwt = false

[functions.handle-oauth-callback]
verify_jwt = false
